version: '3.5'
services:
  ms-base-proxy:
    image: aescobaricc/ms-base-proxy:0.0.3
    container_name: ms-base-proxy
    restart: always
    build: .
    volumes:
     - ./sites-enabled/:/etc/nginx/sites-enabled/ 
     - ./letsencrypt/:/etc/letsencrypt/ 
    ports:
      - "80:80"
      - "443:443"